//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_TO_CART";
export const SET_SHIPPING_TYPE = "SET_SHIPPING_TYPE";
export const RESET_CART_STORE = "RESET_CART_STORE";

//product
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

//auth
export const ON_AUTH_STATE_CHANGED = "ON_AUTH_STATE_CHANGED";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";

export const LOG_OUT_START = "LOG_OUT_START";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAIL = "LOG_OUT_FAIL";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const RESET__ERROR = "RESET_ERROR";

export const RESET_SUCCESS_MESSAGE = "RESET_SUCCESS_MESSAGE";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const UPDATE_DISPLAYNAME_START = "UPDATE_DISPLAYNAME_START";
export const UPDATE_DISPLAYNAME_SUCCESS = "UPDATE_DISPLAYNAME_SUCCESS";
export const UPDATE_DISPLAYNAME_FAIL = "UPDATE_DISPLAYNAME_FAIL";

export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

//order
export const PLACE_ORDER_START = "PLACE_ORDER_START";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const RESET_SUCCESS_STATUS = "RESET_SUCCESS_STATUS";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
